### ISSUE TITLE
Small misprint in AutoMap v1.2.0 TSV output footer

### ISSUE THREAD

**Issue by gtollefson** [mquinodo/AutoMap#10]
Hi,

I'm reporting a small misprint in the `.HomRegions.tsv` output of AutoMap_v1.2.sh. The footer reads 

> ## AutoMap v1.0 used for analysis

Thanks for the great tool. Easy to set up and run and quickly produces easy to understand and useful output.

Best,
George

**Comment by mquinodo** [comment]
Hi George,

Thank you for the report!
It is now corrected.

Best,
Mathieu
