### ISSUE TITLE
How to calculate the fraction of the exome in ROH

### ISSUE THREAD

**Issue by salonso65** [mquinodo/AutoMap#12]
Hi!
I was thinking about how to calculate which percentage of an exome that the total sum of ROH represents (to try to estimate some kind of inbreeding coefficient). My problem is how to estimate the total length of the exome in question according to AutoMap for each sample, and how this depends on teh parametres selected.

Any help?

Thanks in advance

**Comment by mquinodo** [comment]
Hi,
I apologise for the late answer.
I think it is reasonable to use the size a the full genome without N-bases. For hg19 it is 2,897Mb.
Best,
Mathieu

**Comment by salonso65** [comment]
ok, thanks a lot!

santos
