### ISSUE TITLE
--vcflist option not available in v1.2

### ISSUE THREAD

**Issue by skose82** [mquinodo/AutoMap#16]
bash AutoMap_v1.2.sh -h  
bcftools higher or equal to v1.9
bedtools higher or equal to v2.24.0
perl higher or equal to v5.22.0
R higher or equal to v3.2.0
ERROR: Usage: AutoMap_v1.2.sh [--vcf <string>] [--genome <hg19|hg38>] [--out <string>] [--common] [--id <string>] [--panel <string>] [--panelname <string>] [--DP <0-99>] [--binomial <0-1.0>] [--percaltlow <0-1.0>] [--percalthigh <0-1.0>] [--window <3-999>] [--windowthres <1-999>] [--minsize <0-99>] [--minvar <1-999>] [--minperc <0-100>] [--maxgap <0-1000Mb>] [--chrX] [--extend <0-100Mb>]. Exit.
(base)

**Comment by mquinodo** [comment]
It was just missing in the help.
The message has now been corrected.
