### ISSUE TITLE
Can we get the list of variants in the result? 

### ISSUE THREAD

**Issue by DhongiBoi** [mquinodo/AutoMap#17]
After processing the VCF file we get a list of the number of variants, like how many variants were found in each chromosome. Can we get a list of those variants?

```
#Chr	Begin	End	Size(Mb)	Nb_variants	Percentage_homozygosity
chr1	41513572	44129738	2.62	58	89.66
chr1	86447582	89713973	3.27	42	90.48
chr2	128182225	130580573	2.40	27	88.89
chr3	38698526	42184659	3.49	36	91.67
chr4	81447479	88390810	6.94	48	95.83
chr5	139380057	146062570	6.68	85	89.41
chr5	146515817	148402169	1.89	29	93.10
chr6	46716485	47879229	1.16	37	94.59
chr11	47338502	49154505	1.82	26	88.46
chr15	51377428	55196867	3.82	40	92.50
chr19	18938389	22180787	3.24	42	95.24
chr22	27224553	35082493	7.86	81	93.83
```
So I want to know what are the 58 variants in chromosome 1. Is there a way we can get that?

**Comment by mquinodo** [comment]
Dear DhongiBoi,

This option is not available with AutoMap.
However you can use other tools such as vcftools:
vcftools --vcf input.vcf --bed region.bed --out output_prefix --recode --keep-INFO-all
with region.bed containing your region, for example "chr1	41513572	44129738"

Best,
Mathieu
