### ISSUE TITLE
Unable to find locale file in common_analysis.sh

### ISSUE THREAD

**Issue by medjpou** [mquinodo/AutoMap#19]
The following error was observed on running AutoMap_v1.2.sh: 

/home/AutoMap/Scripts/common_analysis.sh: line 83: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory

running "locale" identified the correct files on the local system:

LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

Changed /home/AutoMap/Scripts/common_analysis.sh: line 83: en_US.UTF-8 to en_GB.UTF-8 solved the issue. This similar issue may occur for others where en_US.UTF-8 is not the default locale on the local system.

**Comment by mquinodo** [comment]
As suggested, you need to change your local system settings to en_US.UTF-8.
You can see more details here:
https://www.tecmint.com/set-system-locales-in-linux/
