### ISSUE TITLE
--genome error when using mutiple vcf files

### ISSUE THREAD

**Issue by deb0612** [mquinodo/AutoMap#2]
Dear sir,
I had try to use the command:
bash AutoMap_v1.0.sh --vcf 0366.HC.vcf 0367.HC.vcf 0368.HC.vcf /0369.HC.vcf --out /working_space/ --genome hg38
and got the message below:

_bcftools higher or equal to v1.9
bedtools higher or equal to v2.24.0
perl higher or equal to v5.22.0
R higher or equal to v3.2.0
Parameters used by default:
ERROR: You need to provide the genome version through --genome option (hg19 or hg38). Exit._

I sure I had provided the "--genome" option.

**Comment by mquinodo** [comment]
Dear user,
for the --vcf option, you need to separate the files with commas.
Therefore, the correct command would be:
bash AutoMap_v1.0.sh --vcf 0366.HC.vcf,0367.HC.vcf,0368.HC.vcf,0369.HC.vcf --out /working_space/name --genome hg38
