### ISSUE TITLE
getting bcftools error when running AutoMap_v1.2.sh script on singularity container

### ISSUE THREAD

**Issue by Arth032** [mquinodo/AutoMap#23]
getting below bcftools error when running AutoMap_v1.2.sh script on singularity container

> Homozygosity regions will be extended to nearest variant with maximum of 1 Mb.
/opt/Container/AutoMap/AutoMap_v1.2.sh: line 309: /opt/Container/AutoMap/.log: Read-only file system
## ERROR: The input VCF format is incorrect ('bcftools query -l' was unsuccessful). Exit.

When running bash AutoMap_v1.2.sh on local system its running correctly

![Container](https://github.com/mquinodo/AutoMap/assets/155628220/7dfa8088-54a7-45a7-b751-aab55a153fe8)
![localSystem](https://github.com/mquinodo/AutoMap/assets/155628220/7d8dc75e-af4a-4ac6-9641-2a4df89d39af)

**Comment by mquinodo** [comment]
Hello,
I would change line 219 in the main script from "2> $here/.log" to "2> /dev/null".
Could you tell me if that works?

**Comment by Arth032** [comment]
Sure

**Comment by Fred-07** [comment]
Thanks for providing this program, it is great.
But this "$here/.log" is really a source of problems as the log file is located in the program directory. It would be useful to provide a way to choose a location for the log file, or by default in out directory.

**Comment by mquinodo** [comment]
This is only for internal softwares so it is not relevant information for the AutoMap output.
Now all $here/.log occurences have been removed so there is no more problems.
Thank you again for your feedback.

**Comment by Fred-07** [comment]
Thanks for your reply. I realized that the problem is solved if using v1.3
