### ISSUE TITLE
How small the minimum ROH size threshold can be without losing reliability?

### ISSUE THREAD

**Issue by ManavalanG** [mquinodo/AutoMap#27]
The minimum ROH threshold (`--minsize`) that automap uses by default is 1 Mb. How low can I go in setting this threshold? Is 100kb or 50kb too small a threshold to use?  Is there a threshold below which its accuracy falls significantly in your experience? Thanks!

**Comment by mquinodo** [comment]
Dear Manavalan,
I would try and see how your results look like. As long as you have enough variants in the regions, it should be fine.
Best,
Mathieu
