### ISSUE TITLE
--common error

### ISSUE THREAD

**Issue by abrusell** [mquinodo/AutoMap#3]
When using --common option, after the computation I get this error, just before ending analysis:
AutoMap/Scripts/common_analysis.sh: line 83: printf: 24.8027: invalid number

**Comment by mquinodo** [comment]
Dear user,
The problem could come from LC_NUMERIC.
I edited the script to force LC_NUMERIC="en_US.UTF-8" for the command in question.
It should avoid the previous error.

**Comment by abrusell** [comment]
Ok, it works now!
Thanks
