### ISSUE TITLE
ERROR : AutoMap_v1.0.sh file does not exists (while using v1.2)

### ISSUE THREAD

**Issue by Jjuj66** [mquinodo/AutoMap#6]
Hi,

I'm using latest version (v1.2) and when running the _AutoMap_v1.2.sh_ file, with --multivcf option, I have an error because it's trying to seek the v1.0 bash file.

Command line :
`AutoMap_v1.2.sh --vcf ../multiSample_annotated.vcf.gz --genome hg38 --out multiSample_AutoMap_HM --multivcf`

Error :
```
## Launching analyis for sample: Sample_Name1
bash: /shared/home/user/AutoMap/AutoMap_v1.0.sh: Aucun fichier ou dossier de ce type
 ## Launching analyis for sample: Sample_Name2
bash: /shared/home/user/AutoMap/AutoMap_v1.0.sh: Aucun fichier ou dossier de ce type
```
Aucun fichier ou dossier de ce type -> means can't find the file.

Best,
Julien

**Comment by Jjuj66** [comment]
I manualy replace all the _AutoMap_v1.0_ by _AutoMap_v1.2_ in the _AutoMap_v1.2.sh_ file.
Works fine.

**Comment by mquinodo** [comment]
Dear Julien,

Thank you very much for spotting this error.
I corrected the main file in the repository.

Best,
Mathieu
