### ISSUE TITLE
output.tsv not well sorted

### ISSUE THREAD

**Issue by Jjuj66** [mquinodo/AutoMap#7]
Hi,

I ran AutoMap v1.2, with 2 vcf files, --common and --chrX option.
I've noticed that the output.tsv file in not well sorted by the Begin position.

```
#Chr	Begin	End	Size(Mb)
chr2    114204074       115353814       1.15
chr5    130804987       132560051       1.76
chr8    49371142        50469394        1.10
chr11   73507185        74558585        1.05
chrX	2782116	4985215	2.20
chrX	4985295	9404537	4.42
chrX	9414219	49319525	39.91
chrX	49591026	52857711	3.27
chrX	52862903	55145938	2.28
chrX	55146275	62965055	7.82
chrX	62965138	67415295	4.45
chrX	72794567	74583034	1.79
chrX	67415333	72755923	5.34
chrX	74583402	89204206	14.62
chrX	89207472	119469743	30.26
chrX	119471254	131678991	12.21
chrX	131680824	136873868	5.19
chrX	136874416	141007457	4.13
chrX	144085451	149596554	5.51
chrX	141111645	144078700	2.97
chrX	153605174	155469854	1.86
chrX	150215170	153605159	3.39
```

In this example, the line `chrX	74583402	89204206	14.62` is after the line `chrX	67415333	72755923	5.34`.
Same with `chrX	141111645	144078700	2.97` and `chrX	144085451	149596554	5.51`.

I do not know if it's related with chrX. It's seems not to be important but still, I was confused at first.

Another question how the tools know if a sample is female or male ?

Best,
Julien

**Comment by mquinodo** [comment]
Dear Julien,

Thank you again for your feedback. I corrected the sorting issue.
The tools does not know the sex and analyse the samples agnostically.

Best,
Mathieu
