### ISSUE TITLE
Can it be used on RNA-seq data?

### ISSUE THREAD

**Issue by kvn95ss** [mquinodo/AutoMap#8]
Hello,

Was curious to know if the tool can be used on RNA-seq data, or if some parameters have to be modified to accommodate RNA data.

**Comment by mquinodo** [comment]
Hello,

I did not try it on RNA-Seq data. The results will depend on how many genes are expressed in your experiement.
However without intronic variants close to exon, the performance will be forcibly lower for fro RNA-Seq data, especially for small ROHs.
