### ISSUE TITLE
PASS filtering

### ISSUE THREAD

**Issue by snashraf** [mquinodo/AutoMap#9]
Dear team,

Thanks for the great software!

I have two questions. I have a VCF file generated using GATK.
1. Does the tool filter out the Non PASS calls ?
2. Does the tool filter out the call where ALT is "*"?

Regards,
Najeeb

**Comment by mquinodo** [comment]
Dear Najeeb,

Thank you for your feedback.

1. The tool filters the variants based on various criteria (DP, percent of reads supporting the variant,...). However it does not filter out the non PASS calls.
2. The tool only takes calls with genotype field (GT) equal to 1/1 or 0/1. This excludes multiallelic sites and the ones with "*" described here: https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele-

Best,
Mathieu
